"""create job interests table

Revision ID: a83cc4cedad2
Revises: 3d376cd76359
Create Date: 2026-09-18 01:56:23.625714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83cc4cedad2'
down_revision: Union[str, Sequence[str], None] = '3d376cd76359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'worker_id', name='uq_job_interests_job_worker')
    )
    op.create_index(op.f('ix_job_interests_id'), 'job_interests', ['id'], unique=False)
    op.create_index(op.f('ix_job_interests_job_id'), 'job_interests', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_interests_status'), 'job_interests', ['status'], unique=False)
    op.create_index(op.f('ix_job_interests_worker_id'), 'job_interests', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_interests_worker_id'), table_name='job_interests')
    op.drop_index(op.f('ix_job_interests_status'), table_name='job_interests')
    op.drop_index(op.f('ix_job_interests_job_id'), table_name='job_interests')
    op.drop_index(op.f('ix_job_interests_id'), table_name='job_interests')
    op.drop_table('job_interests')
    # ### end Alembic commands ###
