"""
ML service for MurphAI worker-job matching.

This service connects the FastAPI layer
with the ML inference pipeline.

Responsibilities:

    1. Accept validated API input.
    2. Convert API data into inference features.
    3. Call the champion ML model.
    4. Return a prediction response.

The API route should not contain ML logic directly.
"""


from backend.app.schemas.ml import (
    WorkerJobPredictionRequest,
    WorkerJobPredictionResponse,
)

from ml.src.features.inference_features import (
    prepare_inference_features,
)

from ml.src.inference.champion_predict import (
    predict_with_champion,
)


# ============================================================
# Worker-Job Prediction
# ============================================================


def predict_worker_job_success(
    request: WorkerJobPredictionRequest,
) -> WorkerJobPredictionResponse:
    """
    Predict whether a worker-job interaction will be successful.

    Parameters
    ----------
    request : WorkerJobPredictionRequest
        Raw worker-job information received from the API.

    Returns
    -------
    WorkerJobPredictionResponse
        Prediction generated by the champion ML model.
    """

    # --------------------------------------------------------
    # Step 1: Convert API request into a dictionary
    # --------------------------------------------------------
    #
    # prepare_inference_features() expects a dictionary.
    #

    raw_data = request.model_dump()

    # --------------------------------------------------------
    # Step 2: Prepare inference features
    # --------------------------------------------------------
    #
    # This function:
    #
    #   - validates the raw input
    #   - calculates skill_match_ratio
    #   - calculates skill_gap
    #   - calculates worker_reliability_score
    #   - calculates budget_per_complexity
    #   - creates the DataFrame
    #   - returns features in the exact model order
    #

    inference_features = prepare_inference_features(
        raw_data
    )

    # --------------------------------------------------------
    # Step 3: Run prediction using the champion model
    # --------------------------------------------------------

    prediction = predict_with_champion(
        inference_features
    )

    # --------------------------------------------------------
    # Step 4: Convert ML result into API response
    # --------------------------------------------------------

    return WorkerJobPredictionResponse(
        predicted_success=prediction["predicted_success"],
        success_probability=prediction["success_probability"],
        model_name=prediction["model_name"],
    )